[tools]
node="24.12.0"

[env]
NODE_ENV = "development"

[tasks.dev]
run = "npm run dev"

[tasks.build]
run = "npm run build"

[tasks.start]
run = "npm run start"

[tasks.lint]
run = "npm run lint"

[tasks.test]
run = "npm run test"